### ISSUE TITLE
Not found lsass process handle

### ISSUE THREAD

**Issue by 0xlane** [ricardojoserf/TrickDump#1]
The command line of the `lsass` process on my machine is `C:\Windows\System32\lsass.exe`, which is not equal to `C:\WINDOWS\System32\lsass.exe` in the project, causing the `lsass` process to not be found. It should be converted to lowercase for matching.

**Comment by ricardojoserf** [comment]
Hi @0xlane , thank you for letting me know! I updated the main branch and I will continue updating the rest of the branches today

**Comment by ricardojoserf** [comment]
Hi again, I updated all the branches, please let me know if this problem is solved :)

**Comment by ricardojoserf** [comment]
Hi I think It is fixed, closing for now ;)
